extends:
  - eslint:recommended
  - plugin:prettier/recommended

env:
  browser: false
  node: true
  mocha: true

rules:
  # Allow an escape hatch for unused arguments.
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_(ignored|unused)(_[a-z0-9]+)?'
